package container

import (
	"encoding/hex"
	"testing"

	"go-cipher-cli/internal/testvectors"
)

// Tests for MetaData payload assembly, dual HMAC signing and verification, against
// golden vectors. Expected metaHash/integrityHash were generated by the web tool's
// calculate_meta_data_digest (HMAC-SHA3-512 via @noble/hashes), proving byte-level
// interoperability of the meta-data.json signatures.

func TestMetaData_Payload_GoldenVectors(t *testing.T) {
	v := testvectors.MustLoad()
	for _, c := range v.MetaDataDigest {
		m := &MetaData{
			Version:       c.Version,
			Salt:          c.Salt,
			CreatedAt:     c.CreatedAt,
			SelectedHints: c.SelectedHints,
			SHA256:        c.SHA256,
		}
		got := m.metaPayload()
		if got != c.Payload {
			t.Errorf("payload(%q) =\n got %q\nwant %q", c.Name, got, c.Payload)
		}
	}
}

func TestSignMetaData_GoldenVectors(t *testing.T) {
	v := testvectors.MustLoad()
	for _, c := range v.MetaDataDigest {
		key, _ := hex.DecodeString("7c3156de21f18bcc25a2e2e985a1fbaba01b3a7028398336682ebb9520ddb1000f02ce457a4f653901a709e4c9f00b4d5dd540299824c0e7f1aa92da8771dfdd")
		m := &MetaData{
			Version:       c.Version,
			Salt:          c.Salt,
			CreatedAt:     c.CreatedAt,
			SelectedHints: c.SelectedHints,
			SHA256:        c.SHA256,
		}
		m.SignMetaData(key)
		if m.MetaHash != c.MetaHash {
			t.Errorf("metaHash(%q) = %s, want %s", c.Name, m.MetaHash, c.MetaHash)
		}
		if m.IntegrityHash != c.IntegrityHash {
			t.Errorf("integrityHash(%q) = %s, want %s", c.Name, m.IntegrityHash, c.IntegrityHash)
		}
		// round-trip verify
		if !m.VerifyMetaHash() {
			t.Errorf("VerifyMetaHash(%q) = false, want true", c.Name)
		}
		if !m.VerifyIntegrityHash(key) {
			t.Errorf("VerifyIntegrityHash(%q) = false, want true", c.Name)
		}
	}
}

func TestSignMetaData_NilKeySkipsIntegrity(t *testing.T) {
	m := &MetaData{Version: 1, Salt: "s", SHA256: "x"}
	m.SignMetaData(nil)
	if m.MetaHash == "" {
		t.Fatal("metaHash should be set even with nil key")
	}
	if m.IntegrityHash != "" {
		t.Fatalf("integrityHash should be empty with nil key, got %q", m.IntegrityHash)
	}
	if m.VerifyIntegrityHash(nil) {
		t.Fatal("VerifyIntegrityHash(nil) should be false")
	}
}

func TestVerifyMetaHash_TamperDetected(t *testing.T) {
	m := &MetaData{Version: 1, Salt: "s", SHA256: "x", SelectedHints: []string{"a"}}
	m.SignMetaData(nil)
	original := m.MetaHash
	m.Hint = "tampered" // hint is NOT part of the payload, so metaHash unchanged
	if m.MetaHash != original {
		t.Fatal("changing hint must not alter stored metaHash")
	}
	// tamper a payload field directly
	m.SHA256 = "different"
	if m.VerifyMetaHash() {
		t.Fatal("VerifyMetaHash should detect sha256 tampering")
	}
}

func TestValidateMetaDataFields(t *testing.T) {
	cases := []struct {
		name    string
		md      *MetaData
		wantErr bool
	}{
		{"valid", &MetaData{SHA256: "abc", SelectedHints: []string{}}, false},
		{"empty sha256", &MetaData{SHA256: "  ", SelectedHints: []string{}}, true},
		{"nil hints", &MetaData{SHA256: "abc", SelectedHints: nil}, true},
	}
	for _, c := range cases {
		err := c.md.ValidateMetaDataFields()
		if (err != nil) != c.wantErr {
			t.Errorf("%s: err=%v, wantErr=%v", c.name, err, c.wantErr)
		}
	}
}

func TestMarshalParseMetaData_RoundTrip(t *testing.T) {
	m := &MetaData{
		Version: 10000, Salt: "abc", CreatedAt: 1690000000000,
		Hint: "h", SelectedHints: []string{"a", "b"},
		FileName: "f.txt", FileType: "text/plain", SHA256: "deadbeef",
	}
	raw, err := MarshalMetaData(m)
	if err != nil {
		t.Fatal(err)
	}
	parsed, err := ParseMetaData(raw)
	if err != nil {
		t.Fatal(err)
	}
	if parsed.Version != m.Version || parsed.SHA256 != m.SHA256 ||
		parsed.Hint != m.Hint || len(parsed.SelectedHints) != 2 {
		t.Fatalf("round-trip mismatch: %+v", parsed)
	}
}
