package aesgcm

import (
	"encoding/base64"
	"encoding/hex"
	"sort"
	"strings"
	"testing"

	"go-cipher-cli/internal/safety"
	"go-cipher-cli/internal/testvectors"
)

// TestAuditAllIntermediateFields recomputes EVERY intermediate value of the
// GenerateAesGcmKey pipeline from primitives and compares each to the stored
// golden vector. The vectors were generated by the web tool (noble argon2id +
// HKDF/HMAC), so a green result locks the full AES-key derivation byte-for-byte
// against the frontend.
//
// This complements TestGenerateAesGcmKey_FullPipeline_MatchesGolden, which only
// checks the final aes_dek/sdata; here every stage is asserted, so a regression
// in any primitive (SHA256, HMAC-SHA3-512, HKDF, argon2id, the base64-quirk) is
// caught and pinpointed.
func TestAuditAllIntermediateFields(t *testing.T) {
	if testing.Short() {
		t.Skip("argon2 slow in -short")
	}
	v := testvectors.MustLoad()
	g := v.GenerateAesGcmKey

	// salt_text = SHA256(each pw), sorted, joined by ":"
	hashed := make([]string, len(g.Passwords))
	for i, p := range g.Passwords {
		hashed[i] = safety.SHA256Hex(p)
	}
	sort.Strings(hashed)
	saltText := strings.Join(hashed, ":")
	if saltText != g.SaltText {
		t.Errorf("salt_text:\n got %s\nwant %s", saltText, g.SaltText)
	}

	// salt_prk = HMAC-SHA3-512(key=salt hex-string bytes, data=salt_text)
	saltPrk := safety.HMACSHA3512([]byte(saltText), []byte(g.Salt))
	if saltPrk != g.SaltPRK {
		t.Errorf("salt_prk mismatch")
	}

	// HKDF-derived sub-keys
	s1 := safety.HKDFExpand(saltPrk, []byte("argon2id-salt"), 64)
	s3 := safety.HKDFExpand(saltPrk, []byte("aes-256-gcm-dek"), 64)
	sdata := safety.HKDFExpand(saltPrk, []byte("aes-256-gcm-data"), 64)
	if got := hex.EncodeToString(s1); got != g.S1 {
		t.Errorf("s1:\n got %s\nwant %s", got, g.S1)
	}
	if got := hex.EncodeToString(s3); got != g.S3 {
		t.Errorf("s3:\n got %s\nwant %s", got, g.S3)
	}
	if got := hex.EncodeToString(sdata); got != g.Sdata {
		t.Errorf("sdata:\n got %s\nwant %s", got, g.Sdata)
	}

	// processed passwords: argon2id then base64Decode(hexString) -> hex
	processed := make([]string, len(g.Passwords))
	for i, p := range g.Passwords {
		raw, err := safety.Argon2id([]byte(p), s1, 3, 32*1024, 2, 64)
		if err != nil {
			t.Fatalf("argon2id[%d]: %v", i, err)
		}
		rawHex := hex.EncodeToString(raw)
		if rawHex != g.Argon2RawHex[i] {
			t.Errorf("argon2RawHex[%d]:\n got %s\nwant %s", i, rawHex, g.Argon2RawHex[i])
		}
		quirked, derr := base64.StdEncoding.DecodeString(rawHex)
		if derr != nil {
			quirked = []byte(rawHex) // match the frontend's fallback
		}
		processed[i] = hex.EncodeToString(quirked)
		if processed[i] != g.ProcessedPasswords[i] {
			t.Errorf("processedPasswords[%d]:\n got %s\nwant %s", i, processed[i], g.ProcessedPasswords[i])
		}
	}
	sort.Strings(processed)
	usrStrong := strings.Join(processed, ":")
	if usrStrong != g.UsrStrongKey {
		t.Errorf("usr_strong_key mismatch")
	}

	// prk_dek and final aes_dek
	prkDek := safety.HMACSHA3512([]byte(usrStrong), s3)
	if prkDek != g.PRKDEK {
		t.Errorf("prk_dek:\n got %s\nwant %s", prkDek, g.PRKDEK)
	}
	aesDek := safety.HKDFExpand(prkDek, []byte("aes-256-gcm-final-key"), 32)
	if got := hex.EncodeToString(aesDek); got != g.AesDEK {
		t.Errorf("aes_dek:\n got %s\nwant %s", got, g.AesDEK)
	}
}
