package safety

import (
	"encoding/hex"
	"testing"

	"go-cipher-cli/internal/testvectors"
)

// Tests for AssemblePackageKey against golden vectors. The expected outHex values
// were generated by the web tool's SafetyUtility.strong_derivate_key (noble
// argon2id + HKDF-SHA3-512), so a green result proves byte-level interoperability.

// TestAssemblePackagePassword_GoldenVectors checks the "sort first three, join
// min and max with :" assembly used by the web tool's process_assemble_keys.
func TestAssemblePackagePassword_GoldenVectors(t *testing.T) {
	v := testvectors.MustLoad()
	for _, c := range v.AssemblePackageKey {
		got := assemblePackagePassword(c.Keys)
		if got != c.AssembledPassword {
			t.Errorf("assemblePackagePassword(%v) = %q, want %q", c.Keys, got, c.AssembledPassword)
		}
	}
}

func TestAssemblePackageKey_GoldenVectors(t *testing.T) {
	v := testvectors.MustLoad()
	for _, c := range v.AssemblePackageKey {
		got, err := AssemblePackageKey(c.Keys, c.Salt)
		if err != nil {
			t.Fatalf("AssemblePackageKey(%q): %v", c.Name, err)
		}
		gotHex := hex.EncodeToString(got)
		if gotHex != c.OutHex {
			t.Errorf("AssemblePackageKey(%q) = %s, want %s", c.Name, gotHex, c.OutHex)
		}
		if len(got) != 64 {
			t.Errorf("AssemblePackageKey(%q) len = %d, want 64", c.Name, len(got))
		}
	}
}

func TestAssemblePackageKey_TooFewKeys(t *testing.T) {
	if _, err := AssemblePackageKey([]string{"a", "b"}, "salt"); err == nil {
		t.Fatal("expected error for < 3 keys")
	}
}
