package cmd

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"go-cipher-cli/internal/container"
	"go-cipher-cli/internal/password"
	"go-cipher-cli/internal/safety"
)

// TestDataCipherQuestionAnswerPassword1Rule verifies that a password generated by
// the question-answer high-strength flow (the same one promptPassword1 offers
// during encrypt) satisfies the web tool's password1 composite rule, so it is a
// valid password1.
func TestDataCipherQuestionAnswerPassword1Rule(t *testing.T) {
	if testing.Short() {
		t.Skip("argon2 slow in -short")
	}
	salt := "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	pw, err := password.ComputeFinalPassword(salt, []string{"20240101", "shanghai", "@abc"})
	if err != nil {
		t.Fatalf("compute: %v", err)
	}
	if len(pw) != 128 {
		t.Fatalf("password length = %d, want 128", len(pw))
	}
	if !safety.IsPassword1Valid(pw) {
		t.Fatalf("question-answer password must satisfy the password1 rule")
	}
}

// TestDataCipherEncryptStoresSelectedHints verifies that when password1 was
// generated via the question-answer flow, encrypt stores the chosen question IDs
// in meta-data selectedHints and the bin's salt_seed equals the resolved salt —
// the two inputs decrypt needs to re-answer the questions and reproduce
// password1. It then checks that re-answering those questions with the bin salt
// reproduces the original password (the decrypt restore chain).
func TestDataCipherEncryptStoresSelectedHints(t *testing.T) {
	if testing.Short() {
		t.Skip("argon2 slow in -short")
	}
	salt := "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	answers := []string{"20240101", "shanghai", "@abc"}
	pw1, err := password.ComputeFinalPassword(salt, answers)
	if err != nil {
		t.Fatalf("compute password1: %v", err)
	}

	saveSalt, saveOutput, saveHint := dataCipherSalt, dataCipherOutput, dataCipherHint
	saveKeys, savePw, savePwList, saveHints := dataCipherKeys, dataCipherPassword, dataCipherPasswords, dataCipherSelectedHints
	defer func() {
		dataCipherSalt, dataCipherOutput, dataCipherHint = saveSalt, saveOutput, saveHint
		dataCipherKeys, dataCipherPassword, dataCipherPasswords, dataCipherSelectedHints = saveKeys, savePw, savePwList, saveHints
	}()

	dataCipherSalt = salt
	dataCipherOutput = filepath.Join(t.TempDir(), "bundle.zip")
	dataCipherHint = ""
	dataCipherKeys = []string{dcKeys[0], dcKeys[1], dcKeys[2]}
	dataCipherPassword = pw1
	dataCipherSelectedHints = []string{"Q01", "Q06", "Q23"}

	in := &cipherInput{inputType: "file", data: []byte("payload"), fileName: "secret.txt", mimeType: "text/plain"}
	if err := runEncrypt(in); err != nil {
		t.Fatalf("runEncrypt: %v", err)
	}

	raw, err := os.ReadFile(dataCipherOutput)
	if err != nil {
		t.Fatal(err)
	}
	entries, err := container.DecompressBundle(raw)
	if err != nil {
		t.Fatalf("decompress: %v", err)
	}
	meta, err := container.ParseMetaData(entries.Meta)
	if err != nil {
		t.Fatalf("parse meta: %v", err)
	}
	if !reflect.DeepEqual(meta.SelectedHints, []string{"Q01", "Q06", "Q23"}) {
		t.Fatalf("meta.SelectedHints = %v, want [Q01 Q06 Q23]", meta.SelectedHints)
	}
	parsed, err := container.ExtractDecryptedData(entries.Bin)
	if err != nil {
		t.Fatalf("parse bin: %v", err)
	}
	if parsed.SaltSeed != salt {
		t.Fatalf("bin salt_seed %q != resolved salt %q", parsed.SaltSeed, salt)
	}
	if pw, err := password.ComputeFinalPassword(parsed.SaltSeed, answers); err != nil || pw != pw1 {
		t.Fatalf("re-answer with bin salt must reproduce password1 (err=%v)", err)
	}
}
