package password

import (
	"strings"
	"testing"
)

func TestNormalizePassword(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		{"strips spaces", "  test password  ", "testpassword"},
		{"empty", "", ""},
		{"only spaces", "   ", ""},
		{"cjk", " \u4F60 \u597D \u4E16 \u754C ", "\u4F60\u597D\u4E16\u754C"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := NormalizePassword(tc.in); got != tc.want {
				t.Fatalf("NormalizePassword(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}

func TestNormalizePasswordUnicodeNFC(t *testing.T) {
	a := NormalizePassword("caf\u00E9")
	b := NormalizePassword("cafe\u0301")
	if a != b {
		t.Fatalf("NFC normalization failed: %q vs %q", a, b)
	}
	if a != "caf\u00E9" {
		t.Fatalf("want caf\u00E9, got %q", a)
	}
}

// TestFusePasswordsGolden uses the exact vectors from the web's
// password-fusion.test.ts so the Go port is verified byte-level identical.
func TestFusePasswordsGolden(t *testing.T) {
	passwords := []string{"123456789", "shanghai", "@"}
	cases := []struct {
		salt string
		want string
	}{
		{"a76fdc37b135f1c3", "a4s373h6a9^6ca2f1i5n8d1gfc7h@1b3573"},
		{"cb1045ee07414e4e", "0b5@ee73841asghhe4c1912074.564ie4an"},
		{"b5f6044f2129c682", `b4s253h6a9f&8a266i5n801gc47h@12"29f4`},
		{"857c1eea3013d365", "9{8152773c84a3ahase(6#e510in1g3h53d6@"},
		{"e98310c3be31e633", "e4s393h6a983a236i5(n811ge07h@eb313c"},
		{"d4520ed6e31706f0", "24e@d673817asghh&00d5912e34560i6fan"},
	}
	for _, tc := range cases {
		if got := FusePasswords(tc.salt, passwords); got != tc.want {
			t.Errorf("FusePasswords(%q) = %q, want %q", tc.salt, got, tc.want)
		}
	}
}

func TestFusePasswordsGoldenCJK(t *testing.T) {
	passwords := []string{"123456789", "shanghai\u4E0A\u6D77", "@"}
	cases := []struct {
		salt string
		want string
	}{
		{"cb1045ee07414e4e", "0.b5@ee73841\u6D774ie4he4c191207456asgh\u4E0Aan"},
		{"b5f6044f2129c682", "\u4E0A4b2s356h9\u6D778a\"2f6a568i1nc07g&@42h9142f"},
		{"857c1eea3013d365", "98#152773c841a3a\u6D77h{ase\u4E0A6e50in1g3h5(3d6@"},
		{"e98310c3be31e633", "\u4E0A4e3s396h9\u6D773a286a538i1ne17g@0bh1(ec33"},
		{"d4520ed6e31706f0", "24e@d673817\u6D770i6fh00d5912e3456a&sgh\u4E0Aan"},
	}
	for _, tc := range cases {
		if got := FusePasswords(tc.salt, passwords); got != tc.want {
			t.Errorf("FusePasswords(%q) = %q, want %q", tc.salt, got, tc.want)
		}
	}
}

func TestComputeFinalPasswordGolden(t *testing.T) {
	// Vector generated by the web's PasswordGenerationModal pipeline via
	// common-tools (noble_argon2id p=1 + fusePasswords + hmac_sha3_512 +
	// generate_deterministic_string). Byte-level interop guarantee.
	salt := strings.Repeat("ab", 64)
	passwords := []string{"20240101", "shanghai\u4E0A\u6D77", "@abc"}
	const want = "NKSVKu<EA/G5M~@*vB?4eP^3JEm}>Gn(s(4/`Xq%ps>_`Na-a&0,&8lStCTSli)m||xq|]EvMv*wFwoTo^|Lhg/$OhaeDwxOs@}X<hs,$GYV|w&;I1He(O.}Eu`Ok#,e"
	got, err := ComputeFinalPassword(salt, passwords)
	if err != nil {
		t.Fatalf("ComputeFinalPassword: %v", err)
	}
	if got != want {
		t.Fatalf("password mismatch:\n got %q\nwant %q", got, want)
	}
}

func TestComputeFinalPassword(t *testing.T) {
	salt := strings.Repeat("ab", 64)
	passwords := []string{"20240101", "shanghai\u4E0A\u6D77", "@abc"}
	p1, err := ComputeFinalPassword(salt, passwords)
	if err != nil {
		t.Fatalf("ComputeFinalPassword: %v", err)
	}
	if len(p1) != 128 {
		t.Fatalf("want 128 chars, got %d", len(p1))
	}
	for _, r := range p1 {
		if !strings.ContainsRune(deterministicCharset, r) {
			t.Fatalf("char %q not in charset", r)
		}
	}
	p2, err := ComputeFinalPassword(salt, passwords)
	if err != nil {
		t.Fatalf("ComputeFinalPassword: %v", err)
	}
	if p1 != p2 {
		t.Fatal("ComputeFinalPassword must be deterministic for the same inputs")
	}
	// Different salt must produce a different password.
	p3, err := ComputeFinalPassword(strings.Repeat("cd", 64), passwords)
	if err != nil {
		t.Fatalf("ComputeFinalPassword: %v", err)
	}
	if p3 == p1 {
		t.Fatal("different salts must produce different passwords")
	}
}

func TestDeriveNewSaltFallback(t *testing.T) {
	// Empty original salt falls back to the default salt, still non-empty.
	got, err := DeriveNewSalt("")
	if err != nil {
		t.Fatalf("DeriveNewSalt: %v", err)
	}
	if len(got) == 0 {
		t.Fatal("derived salt must be non-empty")
	}
}
